Preview modules workflow changes (#243)
* fix for reading secret

* fix for reading secret

* updated to single quotes

* updated the logic  of reading the control planes json

* updated the logic  of creating the control planes json

* Updated preview.yml to work with control_planes.json

* Updated preview.yml to use format function for dynamic token retrieval

* added TOKEN_REF_NAME

* update to get the module directory path

* using all secrets

* added a cat command

* updated the jq commands

* updating the sample version as well

* updating the sample version as well

* updated the script to fail if any command failed

* testing fail scenario

* Revert "testing fail scenario"

This reverts commit 0d25918ceff41a1fdd4e82b8bacc2d9abfe87e8d.

* added a few assertions

* updated the variables name

diff --git a/.github/workflows/preview.yml b/.github/workflows/preview.yml
--- a/.github/workflows/preview.yml
+++ b/.github/workflows/preview.yml
@@ -32,31 +32,52 @@ jobs:
         with:
           ref: ${{ github.ref }}
 
-      - name: Set control planes variable
+      - name: Create control planes JSON file
         id: set_control_planes
         run: |
           set -e
-          echo "CONTROL_PLANES=${{ vars.control_planes }}" >> $GITHUB_ENV
+          set -o pipefail
+          JSON_CONTENT='${{ vars.DEV_CONTROL_PLANES }}'
+          echo "$JSON_CONTENT" > control_planes.json
 
       - name: Get module directory path
         id: get_module_path
         run: |
           set -e
-          MODULE_DIR_PATH=$(echo "${CONTROL_PLANES}" | jq -r ".[] | select(.intent == \"${{ github.event.inputs.intent }}\" and .flavor == \"${{ github.event.inputs.flavor }}\" and .version == \"${{ github.event.inputs.version }}\") | .relativePath")
+          MODULE_DIR_PATH=$(jq -r ".[] | select(.intent == \"${{ github.event.inputs.intent }}\" and .flavor == \"${{ github.event.inputs.flavor }}\" and .version == \"${{ github.event.inputs.version }}\") | .relativePath" index.json)
+
+          # Check if MODULE_DIR_PATH is found
+          if [ -z "$MODULE_DIR_PATH" ]; then
+            echo "Error: Module directory path not found for the intent ${{ github.event.inputs.intent }} flavor ${{ github.event.inputs.flavor }} version ${{ github.event.inputs.version }}."
+            exit 1
+          fi
+
           echo "MODULE_DIR_PATH=$MODULE_DIR_PATH" >> $GITHUB_ENV
+          echo "MODULE_DIR_PATH=$MODULE_DIR_PATH"
 
       - name: Update facets.yaml version
         run: |
           set -e
+          set -o pipefail
           GITHUB_REF="${{ github.ref }}"
           FACETS_YAML_PATH="$MODULE_DIR_PATH/facets.yaml"
+          # Check if facets.yaml exists
+          if [ ! -f "$FACETS_YAML_PATH" ]; then
+            echo "Error: facets.yaml not found in the module directory."
+            exit 1
+          fi
+
           echo "Updating version in $FACETS_YAML_PATH"
           # Append the GitHub ref to the version in facets.yaml
           yq eval -i ".version += \"-${GITHUB_REF}\"" "$FACETS_YAML_PATH"
+          yq eval -i ".sample.version += \"-${GITHUB_REF}\"" "$FACETS_YAML_PATH"
 
       - name: Execute command
+        env:
+          ALL_SECRETS: ${{ toJson(secrets) }}
         run: |
           set -e
+          set -o pipefail
           if [ -n "${{ github.event.inputs.url }}" ] && [ -n "${{ github.event.inputs.username }}" ] && [ -n "${{ github.event.inputs.token }}" ]; then
             # Use provided URL, Username, and Token
             URL="${{ github.event.inputs.url }}"
@@ -67,14 +88,15 @@ jobs:
           else
             echo "Processing all control planes concurrently."
             # Loop through all control planes and run commands in parallel
-            for key in $(echo "${CONTROL_PLANES}" | jq -r 'keys[]'); do
-              URL=$(echo "${CONTROL_PLANES}" | jq -r ".[$key].URL")
-              USERNAME=$(echo "${CONTROL_PLANES}" | jq -r ".[$key].Username")
-              TOKEN_REF_NAME=$(echo "${CONTROL_PLANES}" | jq -r ".[$key].TokenRef") 
-              TOKEN="${{ secrets[TOKEN_REF_NAME] }}"
-              echo "Starting process for control plane: $key"
-              curl -s https://facets-cloud.github.io/facets-schemas/scripts/module_register.sh | bash -s -- -c "$URL" -u "$USERNAME" -t "$TOKEN" -p "$MODULE_DIR_PATH" &
+            for key in $(jq -r 'keys[]' control_planes.json); do
+              URL=$(jq -r ".$key.URL" control_planes.json)
+              USERNAME=$(jq -r ".$key.Username" control_planes.json)
+              TOKEN_REF_NAME=$(jq -r ".$key.TokenRef" control_planes.json)
+              TOKEN=$(echo "$ALL_SECRETS" | jq -r ".\"$TOKEN_REF_NAME\"")
+              echo "Registering to control plane $key"
+              curl -s https://facets-cloud.github.io/facets-schemas/scripts/module_register.sh | bash -s -- -c "$URL" -u "$USERNAME" -t "$TOKEN" -p "$MODULE_DIR_PATH"
             done
-            echo "Waiting for all background processes to complete..."
-            wait # Wait for all background processes to finish
+
+            # Wait for all background processes and check for errors
+            wait
           fi
